<#
.SYNOPSIS
    Sets up a fresh Windows 11 machine: Git for Windows (incl. Git Bash), dotfiles,
    and a shared ssh-agent socket for Git Bash, PowerShell and VS Code.

.DESCRIPTION
    Safe to re-run: existing files that differ are backed up to <file>.bak, and
    profile lines, env vars and the logon task are only added/updated once.

    Fresh machine (no git yet), from Windows PowerShell:
        & ([scriptblock]::Create((irm https://raw.githubusercontent.com/ebgenius/dotfiles/main/windows/install.ps1)))

    From a clone:
        powershell -ExecutionPolicy Bypass -File windows\install.ps1

.PARAMETER Machine
    Install Git for all users (needs admin) instead of the current user only.
#>
param(
    [switch]$Machine,
    [string]$RepoDir = "$HOME\workspaces\dotfiles"
)

$ErrorActionPreference = 'Stop'
$repoUrl  = 'https://github.com/ebgenius/dotfiles.git'
$taskName = 'SSH Agent (Git socket)'

function Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }

function Update-SessionPath {
    $env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
                [Environment]::GetEnvironmentVariable('Path', 'User')
}

# ---------------------------------------------------------------- Git for Windows
Step 'Git for Windows'
if (Get-Command git -ErrorAction SilentlyContinue) {
    Write-Host "    already installed: $(git --version)"
} else {
    if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
        throw 'winget not found. Install "App Installer" from the Microsoft Store, then re-run.'
    }
    $scope = if ($Machine) { 'machine' } else { 'user' }
    winget install --id Git.Git --exact --source winget --scope $scope `
        --accept-package-agreements --accept-source-agreements --silent
    if ($LASTEXITCODE -ne 0) { throw "winget failed to install Git (exit $LASTEXITCODE)" }
    Update-SessionPath
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw 'git still not on PATH after install' }
    Write-Host "    installed: $(git --version)"
}

# ---------------------------------------------------------------- dotfiles repo
# When run as a downloaded scriptblock there is no script file, so clone the repo first.
$srcRoot = if ($PSScriptRoot) { $PSScriptRoot } else { $null }
if (-not $srcRoot) {
    Step "Cloning dotfiles to $RepoDir"
    if (-not (Test-Path "$RepoDir\.git")) {
        New-Item -ItemType Directory -Force (Split-Path $RepoDir) | Out-Null
        git clone $repoUrl $RepoDir
        if ($LASTEXITCODE -ne 0) { throw 'git clone failed' }
    } else {
        Write-Host '    already cloned'
    }
    $srcRoot = "$RepoDir\windows"
}

# ---------------------------------------------------------------- home files
Step 'Copying dotfiles to home'
$homeSrc = Join-Path $srcRoot 'home'
Get-ChildItem $homeSrc -Recurse -File -Force | ForEach-Object {
    $rel  = $_.FullName.Substring($homeSrc.Length + 1)
    $dest = Join-Path $HOME $rel
    New-Item -ItemType Directory -Force (Split-Path $dest) | Out-Null
    if (Test-Path $dest) {
        if ((Get-FileHash $dest).Hash -eq (Get-FileHash $_.FullName).Hash) {
            Write-Host "    unchanged  ~\$rel"; return
        }
        Copy-Item $dest "$dest.bak" -Force
        Write-Host "    updated    ~\$rel (old copy: $rel.bak)"
    } else {
        Write-Host "    created    ~\$rel"
    }
    Copy-Item $_.FullName $dest -Force
}

# Git Bash only reads ~/.bashrc via ~/.bash_profile; Git creates it on first launch,
# but we need it now so the very first Git Bash window already has the agent.
if (-not (Test-Path "$HOME\.bash_profile")) {
    "# generated by Git for Windows`ntest -f ~/.profile && . ~/.profile`ntest -f ~/.bashrc && . ~/.bashrc`n" |
        Set-Content "$HOME\.bash_profile" -NoNewline -Encoding ascii
    Write-Host '    created    ~\.bash_profile'
}

# ---------------------------------------------------------------- PowerShell profiles
Step 'PowerShell profiles (Windows PowerShell 5.1 and PowerShell 7)'
$docs = [Environment]::GetFolderPath('MyDocuments')   # follows OneDrive redirection
$line = '& "$HOME\.ssh\ensure-agent.ps1"'
foreach ($p in "$docs\WindowsPowerShell\Microsoft.PowerShell_profile.ps1",
               "$docs\PowerShell\Microsoft.PowerShell_profile.ps1") {
    New-Item -ItemType Directory -Force (Split-Path $p) | Out-Null
    if ((Test-Path $p) -and (Select-String -Path $p -SimpleMatch $line -Quiet)) {
        Write-Host "    unchanged  $p"
    } else {
        Add-Content -Path $p -Value "`r`n# SSH agent on shared socket (also used by Git Bash and VS Code)`r`n$line"
        Write-Host "    updated    $p"
    }
}
# Profiles are scripts; the Windows client default policy (Restricted) would block them.
if ((Get-ExecutionPolicy -Scope CurrentUser) -in 'Undefined', 'Restricted') {
    # 5.1 can throw "Security error." even though the policy was written, so check the result.
    try { Set-ExecutionPolicy -Scope CurrentUser RemoteSigned -Force } catch { }
    if ((Get-ExecutionPolicy -Scope CurrentUser) -eq 'RemoteSigned') {
        Write-Host '    execution policy (CurrentUser) -> RemoteSigned'
    } else {
        Write-Warning 'Could not set execution policy; PowerShell profiles may not run.'
    }
}

# ---------------------------------------------------------------- SSH_AUTH_SOCK
Step 'SSH_AUTH_SOCK user environment variable'
$sock = "$HOME/.ssh/agent.sock" -replace '\\', '/'
[Environment]::SetEnvironmentVariable('SSH_AUTH_SOCK', $sock, 'User')
$env:SSH_AUTH_SOCK = $sock
Write-Host "    $sock"

# ---------------------------------------------------------------- logon task
Step "Scheduled task '$taskName' (starts the agent at logon)"
$shell = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
if (-not $shell) { $shell = (Get-Command powershell).Source }
$action   = New-ScheduledTaskAction -Execute $shell -Argument (
    "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$HOME\.ssh\ensure-agent.ps1`"")
$trigger  = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 2)
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
Write-Host '    registered'

# ---------------------------------------------------------------- start agent now
Step 'Starting ssh-agent'
$ErrorActionPreference = 'Continue'
& "$HOME\.ssh\ensure-agent.ps1"
$keys = Get-ChildItem "$HOME\.ssh\id_*" -File -ErrorAction SilentlyContinue | Where-Object Extension -ne '.pub'
if ($keys) {
    ssh-add -l
} else {
    Write-Warning 'No private keys found in ~\.ssh (id_*). Copy or generate them, then open a new shell.'
}

Write-Host ''
Write-Host 'Done. Restart VS Code (all windows) so it picks up SSH_AUTH_SOCK.' -ForegroundColor Green
